global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "render-spring-app"
    metrics_path: "/actuator/prometheus"
    scheme: https
    static_configs:
      - targets: ["dapp-grupop-2025s2.onrender.com"]
tls_config:
  insecure_skip_verify: true