name: CI - Build and Test

on:
  push:
    branches:
      - "main"
      - "TP-2"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c칩digo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # OpenJDK Temurin
          java-version: '21'        # O la versi칩n que uses

      # 3. Cache de dependencias Gradle (para hacerlo m치s r치pido)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Dar permisos a gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. Compilar y ejecutar tests
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with coverage
        run: ./gradlew clean test jacocoTestReport

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      - name: SonarCloud Scan
        run: ./gradlew sonarqube -Dsonar.projectKey=ignacioferro80_dapp-grupoP-2025s2 -Dsonar.organization=ignacioferro80 -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}